"""
==============================================================================
EIMS Asset Registry Asynchronous Repository & Read-Through Cache Layer
Governed by EIMS Documentation System (EDS v1.0.0) - Core Law 3 & 4 Compliance
Source-Available All Rights Reserved Policy
==============================================================================
"""

import json
import uuid
from typing import Optional, List, Dict, Any
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.domain.asset_registry.models import InfrastructureAsset, AuditLog, OCRRegistrationRecord
from backend.domain.asset_registry.state_machine import AssetLifecycleStateMachine, AssetState
from backend.infrastructure.cache import AsynchronousCacheManager
from backend.core.exceptions import ResourceNotFoundException
from backend.core.logger import get_logger

logger = get_logger("eims.domain.repository")

# Canonical Redis Key Namespace mapping per Core Law 4 Section 7.3
ASSET_CACHE_KEY_PREFIX = "eims:asset:"
ASSET_CACHE_TTL_SECONDS = 300  # 5 minutes volatile-LRU cache limit


class AssetRepository:
    """
    Authoritative data access encapsulation layer insulating REST Controllers from direct SQL.
    Orchestrates ACID transactions across PostgreSQL (via PgBouncer) alongside volatile-LRU Redis caching.
    """
    def __init__(self, db_session: AsyncSession, cache_manager: AsynchronousCacheManager):
        self.db_session = db_session
        self.cache_manager = cache_manager

    def _get_cache_key(self, asset_id: uuid.UUID | str) -> str:
        """Constructs compliant Redis namespace storage string."""
        return f"{ASSET_CACHE_KEY_PREFIX}{str(asset_id)}"

    def _serialize_asset_for_cache(self, asset: InfrastructureAsset) -> Dict[str, Any]:
        """Converts ORM entity attributes into clean JSON-serializable dictionary format."""
        return {
            "asset_id": str(asset.asset_id),
            "hostname": asset.hostname,
            "canonical_ip": asset.canonical_ip,
            "cryptographic_fingerprint": asset.cryptographic_fingerprint,
            "lifecycle_state": asset.lifecycle_state,
            "current_compliance_score": asset.current_compliance_score,
            "created_at": asset.created_at.isoformat() if asset.created_at else None,
            "updated_at": asset.updated_at.isoformat() if asset.updated_at else None,
            "offline_report_data": asset.offline_report_data if hasattr(asset, 'offline_report_data') else None,
        }

    async def create_asset(
        self,
        hostname: str,
        canonical_ip: str,
        cryptographic_fingerprint: str,
        actor_id: Optional[uuid.UUID] = None
    ) -> InfrastructureAsset:
        """
        Registers a newly discovered compute resource, sets status to Discovered,
        records an atomic AuditLog initialization entry, and populates volatile Redis cache.
        """
        new_asset = InfrastructureAsset(
            hostname=hostname,
            canonical_ip=canonical_ip,
            cryptographic_fingerprint=cryptographic_fingerprint,
            lifecycle_state=AssetState.DISCOVERED.value,
            current_compliance_score=0
        )
        self.db_session.add(new_asset)
        await self.db_session.flush()  # Populates autogenerated UUID primary key prior to commit

        # Create atomic initial audit trail record within identical ACID transaction scope
        audit_entry = AuditLog(
            actor_id=actor_id,
            asset_id=new_asset.asset_id,
            action_verb="ENROLL_ASSET",
            immutable_payload={
                "event": "Initial Discovery Agent mTLS Enrollment",
                "hostname": hostname,
                "canonical_ip": canonical_ip,
                "assigned_state": AssetState.DISCOVERED.value
            }
        )
        self.db_session.add(audit_entry)
        await self.db_session.commit()
        await self.db_session.refresh(new_asset)

        # Populate Redis Read-Through Cache
        cache_key = self._get_cache_key(new_asset.asset_id)
        await self.cache_manager.set_value(cache_key, self._serialize_asset_for_cache(new_asset), ttl_seconds=ASSET_CACHE_TTL_SECONDS)
        
        logger.info(f"Successfully registered asset '{hostname}' (ID: {new_asset.asset_id}) with initial status 'Discovered'.")
        return new_asset

    async def get_asset_by_id(self, asset_id: uuid.UUID) -> Optional[InfrastructureAsset]:
        """
        Implements high-speed Read-Through cache lookup. Interrogates volatile Redis in-memory
        structures prior to querying relational database connection pools.
        """
        cache_key = self._get_cache_key(asset_id)
        cached_raw = await self.cache_manager.get_value(cache_key)
        
        # If cache hit occurs, we still execute lightweight session extraction or construct ORM state if strictly necessary,
        # but to ensure full SQLAlchemy session relationship viability in our service layer, we verify via primary query while updating cache.
        query = select(InfrastructureAsset).where(InfrastructureAsset.asset_id == asset_id)
        result = await self.db_session.execute(query)
        asset = result.scalar_one_or_none()
        
        if asset:
            # Refresh Redis volatile cache TTL
            await self.cache_manager.set_value(cache_key, self._serialize_asset_for_cache(asset), ttl_seconds=ASSET_CACHE_TTL_SECONDS)
            
        return asset

    async def get_asset_by_fingerprint(self, fingerprint: str) -> Optional[InfrastructureAsset]:
        """Searches index table for SHA-256 hardware serial signature matches."""
        query = select(InfrastructureAsset).where(InfrastructureAsset.cryptographic_fingerprint == fingerprint)
        result = await self.db_session.execute(query)
        return result.scalar_one_or_none()

    async def transition_state(
        self,
        asset_id: uuid.UUID,
        target_state: str,
        actor_id: Optional[uuid.UUID] = None,
        reason: str = "Automated policy evaluation"
    ) -> InfrastructureAsset:
        """
        Executes state machine validation and atomically commits status mutation alongside an
        immutable AuditLog historical delta record (Core Law 3 & 4 Compliance).
        """
        asset = await self.get_asset_by_id(asset_id)
        if not asset:
            raise ResourceNotFoundException(resource_type="InfrastructureAsset", resource_id=str(asset_id))

        current_state = asset.lifecycle_state
        # Validate proposed transition against immutable Core Law 3 state matrix
        AssetLifecycleStateMachine.validate_transition(
            current_state=current_state,
            target_state=target_state,
            asset_id=str(asset_id)
        )

        # Apply state modification
        asset.lifecycle_state = target_state

        # Record atomic mutation entry inside immutable audit journal
        audit_entry = AuditLog(
            actor_id=actor_id,
            asset_id=asset.asset_id,
            action_verb="TRANSITION_STATE",
            immutable_payload={
                "previous_state": current_state,
                "new_state": target_state,
                "reason": reason,
                "compliance_score_at_transition": asset.current_compliance_score
            }
        )
        self.db_session.add(audit_entry)
        await self.db_session.commit()
        await self.db_session.refresh(asset)

        # Invalidate and re-populate volatile Redis representation
        cache_key = self._get_cache_key(asset.asset_id)
        await self.cache_manager.set_value(cache_key, self._serialize_asset_for_cache(asset), ttl_seconds=ASSET_CACHE_TTL_SECONDS)

        logger.info(f"Asset '{asset.asset_id}' transitioned successfully: [{current_state}] -> [{target_state}].")
        return asset

    async def list_assets(self, skip: int = 0, limit: int = 50, state: Optional[str] = None) -> List[InfrastructureAsset]:
        """Retrieves paginated asset collections with optional status filtering."""
        query = select(InfrastructureAsset).offset(skip).limit(limit)
        if state:
            query = query.where(InfrastructureAsset.lifecycle_state == state)
        result = await self.db_session.execute(query)
        return list(result.scalars().all())

    async def create_ocr_registration(self, minio_uri: str) -> OCRRegistrationRecord:
        """Asynchronously records a newly uploaded asset document to initiate OCR pipeline."""
        tracking_record = OCRRegistrationRecord(
            minio_object_uri=minio_uri,
            extraction_status="Pending",
            parsed_raw_text={}
        )
        self.db_session.add(tracking_record)
        await self.db_session.commit()
        await self.db_session.refresh(tracking_record)
    async def upsert_offline_report(self, report_data: dict) -> InfrastructureAsset:
        """Processes an offline USB Auditor JSON report, upserting the asset and its compliance score."""
        system_info = report_data.get("system", {})
        hostname = system_info.get("computer_name", "UNKNOWN_HOST")
        canonical_ip = system_info.get("ip_address", "0.0.0.0")
        fingerprint = system_info.get("mac_address", "00:00:00:00:00:00")
        compliance_score = report_data.get("compliance_score", 0)
        
        target_state = AssetState.NON_COMPLIANT.value if compliance_score < 70 else AssetState.COMPLIANT.value

        # Check if asset exists by fingerprint or hostname
        query = select(InfrastructureAsset).where(
            (InfrastructureAsset.cryptographic_fingerprint == fingerprint) |
            (InfrastructureAsset.hostname == hostname)
        )
        result = await self.db_session.execute(query)
        asset = result.scalar_one_or_none()

        if not asset:
            # Create new
            asset = InfrastructureAsset(
                hostname=hostname,
                canonical_ip=canonical_ip,
                cryptographic_fingerprint=fingerprint,
                lifecycle_state=target_state,
                current_compliance_score=compliance_score,
                offline_report_data=report_data
            )
            self.db_session.add(asset)
            await self.db_session.flush() # Ensure we get the asset_id for the AuditLog
            
            audit_entry = AuditLog(
                asset_id=asset.asset_id,
                action_verb="IMPORT_REPORT",
                immutable_payload={"event": "Offline USB Auditor Import", "score": compliance_score}
            )
            self.db_session.add(audit_entry)
        else:
            # Update existing
            asset.hostname = hostname
            asset.canonical_ip = canonical_ip
            asset.lifecycle_state = target_state
            asset.current_compliance_score = compliance_score
            asset.offline_report_data = report_data
            
            audit_entry = AuditLog(
                asset_id=asset.asset_id,
                action_verb="UPDATE_FROM_REPORT",
                immutable_payload={"event": "Offline USB Auditor Update", "new_score": compliance_score}
            )
            self.db_session.add(audit_entry)

        await self.db_session.commit()
        await self.db_session.refresh(asset)

        # Update cache
        cache_key = self._get_cache_key(asset.asset_id)
        await self.cache_manager.set_value(cache_key, self._serialize_asset_for_cache(asset), ttl_seconds=ASSET_CACHE_TTL_SECONDS)

        return asset
