"""Add offline_report_data to InfrastructureAsset
==============================================================================
EIMS Database Schema Revision: 0b701e021a8f
Governed by EIMS Documentation System (EDS v1.0.0) - Core Law 4 Compliance
==============================================================================

Revision ID: 0b701e021a8f
Revises: 055005f43679
Create Date: 2026-08-11 13:19:33.177237
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b701e021a8f'
down_revision: Union[str, None] = '055005f43679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Executes forward declarative schema migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_assets', sa.Column('offline_report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts schema mutations to previous down_revision state."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infrastructure_assets', 'offline_report_data')
    # ### end Alembic commands ###
