"""Add OCRRegistrationRecord
==============================================================================
EIMS Database Schema Revision: 1a78de93777d
Governed by EIMS Documentation System (EDS v1.0.0) - Core Law 4 Compliance
==============================================================================

Revision ID: 1a78de93777d
Revises: 
Create Date: 2026-08-10 15:35:34.072625
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a78de93777d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Executes forward declarative schema migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_assets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('canonical_ip', sa.String(length=45), nullable=False),
    sa.Column('cryptographic_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('current_compliance_score', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_compliance_score >= 0 AND current_compliance_score <= 100', name='ck_asset_compliance_score_bounds'),
    sa.PrimaryKeyConstraint('asset_id'),
    comment='Core Asset Registry Table governed under Core Law 4.'
    )
    op.create_index(op.f('ix_infrastructure_assets_cryptographic_fingerprint'), 'infrastructure_assets', ['cryptographic_fingerprint'], unique=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('action_verb', sa.String(length=64), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('immutable_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['infrastructure_assets.asset_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='Immutable audit transaction journal governed under Core Law 4.'
    )
    op.create_index('idx_audit_logs_action_time', 'audit_logs', ['action_verb', 'performed_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_verb'), 'audit_logs', ['action_verb'], unique=False)
    op.create_index(op.f('ix_audit_logs_asset_id'), 'audit_logs', ['asset_id'], unique=False)
    op.create_table('hardware_inventories',
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('cpu_sku_model', sa.String(length=128), nullable=False),
    sa.Column('total_ram_mb', sa.Integer(), nullable=False),
    sa.Column('storage_topology', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_audited_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_ram_mb >= 0', name='ck_hardware_inventory_ram_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['infrastructure_assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inventory_id'),
    comment='Hardware inventories containing polymorphic GIN-indexed storage topologies.'
    )
    op.create_index('idx_hardware_storage_gin', 'hardware_inventories', ['storage_topology'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_hardware_inventories_asset_id'), 'hardware_inventories', ['asset_id'], unique=False)
    op.create_table('ocr_registration_records',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('minio_object_uri', sa.String(length=512), nullable=False),
    sa.Column('extraction_status', sa.String(length=32), nullable=False),
    sa.Column('parsed_raw_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['infrastructure_assets.asset_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('minio_object_uri'),
    comment='OCR Registration workflow tracking governed under Core Law 4.'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts schema mutations to previous down_revision state."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_registration_records')
    op.drop_index(op.f('ix_hardware_inventories_asset_id'), table_name='hardware_inventories')
    op.drop_index('idx_hardware_storage_gin', table_name='hardware_inventories', postgresql_using='gin')
    op.drop_table('hardware_inventories')
    op.drop_index(op.f('ix_audit_logs_asset_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_verb'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_infrastructure_assets_cryptographic_fingerprint'), table_name='infrastructure_assets')
    op.drop_table('infrastructure_assets')
    # ### end Alembic commands ###
