import pgvector
"""add_analyzer_tables
==============================================================================
EIMS Database Schema Revision: 5811549d7120
Governed by EIMS Documentation System (EDS v1.0.0) - Core Law 4 Compliance
==============================================================================

Revision ID: 5811549d7120
Revises: 4a4cc8514d35
Create Date: 2026-08-12 05:58:18.092451
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5811549d7120'
down_revision: Union[str, None] = '4a4cc8514d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    """Executes forward declarative schema migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('solution_json', sa.JSON(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_knowledge_event_id'), 'ai_knowledge', ['event_id'], unique=False)
    op.create_index(op.f('ix_ai_knowledge_id'), 'ai_knowledge', ['id'], unique=False)
    op.create_table('analysis_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('parse_method', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ai_summary', sa.String(), nullable=True),
    sa.Column('solution_summary', sa.JSON(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('search_results', sa.JSON(), nullable=True),
    sa.Column('search_time_ms', sa.Float(), nullable=True),
    sa.Column('feedback_score', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('feedback_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_history_event_id'), 'analysis_history', ['event_id'], unique=False)
    op.create_index(op.f('ix_analysis_history_id'), 'analysis_history', ['id'], unique=False)
    op.create_index(op.f('ix_analysis_history_provider'), 'analysis_history', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts schema mutations to previous down_revision state."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_analysis_history_provider'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_id'), table_name='analysis_history')
    op.drop_index(op.f('ix_analysis_history_event_id'), table_name='analysis_history')
    op.drop_table('analysis_history')
    op.drop_index(op.f('ix_ai_knowledge_id'), table_name='ai_knowledge')
    op.drop_index(op.f('ix_ai_knowledge_event_id'), table_name='ai_knowledge')
    op.drop_table('ai_knowledge')
    # ### end Alembic commands ###
