"""Update ServiceEvaluation to 1-to-N and add responder details
==============================================================================
EIMS Database Schema Revision: 666758c0b236
Governed by EIMS Documentation System (EDS v1.0.0) - Core Law 4 Compliance
==============================================================================

Revision ID: 666758c0b236
Revises: 0b701e021a8f
Create Date: 2026-08-12 05:10:28.104162
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666758c0b236'
down_revision: Union[str, None] = '0b701e021a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Executes forward declarative schema migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_evaluations', sa.Column('responder_name', sa.String(length=255), nullable=True))
    op.add_column('service_evaluations', sa.Column('department', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('service_evaluations_session_id_key'), 'service_evaluations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts schema mutations to previous down_revision state."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('service_evaluations_session_id_key'), 'service_evaluations', ['session_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('service_evaluations', 'department')
    op.drop_column('service_evaluations', 'responder_name')
    # ### end Alembic commands ###
