"""add_telemetry_and_winlog_tables
==============================================================================
EIMS Database Schema Revision: 8f223874fe15
Governed by EIMS Documentation System (EDS v1.0.0) - Core Law 4 Compliance
==============================================================================

Revision ID: 8f223874fe15
Revises: 1a78de93777d
Create Date: 2026-08-11 10:02:50.669350
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f223874fe15'
down_revision: Union[str, None] = '1a78de93777d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Executes forward declarative schema migrations."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_utilization', sa.Float(), nullable=False),
    sa.Column('diagnostic_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['infrastructure_assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id'),
    comment='High-frequency operational metrics governed under Core Law 4.'
    )
    op.create_index('idx_telemetry_asset_time', 'telemetry_metrics', ['asset_id', 'event_time'], unique=False)
    op.create_table('windows_event_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('occurrence_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('severity_level', sa.String(length=16), nullable=False),
    sa.Column('evtx_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['infrastructure_assets.asset_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('log_id'),
    comment='Windows diagnostic logs featuring polymorphic GIN-indexed metadata.'
    )
    op.create_index('idx_winlog_metadata_gin', 'windows_event_logs', ['evtx_metadata'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts schema mutations to previous down_revision state."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_winlog_metadata_gin', table_name='windows_event_logs', postgresql_using='gin')
    op.drop_table('windows_event_logs')
    op.drop_index('idx_telemetry_asset_time', table_name='telemetry_metrics')
    op.drop_table('telemetry_metrics')
    # ### end Alembic commands ###
