"""
==============================================================================
EIMS Telemetry Domain ORM Models & GIN Index Architecture
Governed by EIMS Documentation System (EDS v1.0.0) - Core Law 4 Section 6.2 & 7.1
Source-Available All Rights Reserved Policy
==============================================================================
"""

import uuid
from datetime import datetime, timezone
from typing import Optional, Dict, Any
from sqlalchemy import (
    Column,
    String,
    Integer,
    Float,
    DateTime,
    ForeignKey,
    Index,
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.infrastructure.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class TelemetryMetric(Base):
    """
    Time-series repository entity storing computational runtime health metrics
    emitted continuously by remote Discovery Agents (Core Law 4 Section 6.2).
    """
    __tablename__ = "telemetry_metrics"

    metric_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc="Universally unique metric record identifier."
    )
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("infrastructure_assets.asset_id", ondelete="CASCADE"),
        nullable=False,
        doc="Foreign key reference binding metrics to origin compute asset."
    )
    event_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        doc="Timestamp of physical metric sampling occurrence (UTC)."
    )
    cpu_utilization: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        doc="Recorded CPU utilization percentage (0.0 to 100.0)."
    )
    diagnostic_payload: Mapped[Dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        doc="Extensible JSON attribute dictionary capturing RAM, IOPS, and network bandwidth."
    )

    __table_args__ = (
        Index("idx_telemetry_asset_time", "asset_id", "event_time"),
        {"comment": "High-frequency operational metrics governed under Core Law 4."}
    )


class WindowsEventLog(Base):
    """
    Stores structural Windows Operating System diagnostic and security events captured
    during continuous log inspection. Features polymorphic GIN Indexing.
    """
    __tablename__ = "windows_event_logs"

    log_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        doc="Unique log event processing record ID."
    )
    asset_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("infrastructure_assets.asset_id", ondelete="CASCADE"),
        nullable=False,
        doc="Host asset that generated the native .evtx stream event."
    )
    occurrence_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        doc="Precise timestamp generated by origin operating system eventing."
    )
    event_id: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        doc="Canonical Windows Event Log numeric identifier (e.g., 4624, 4625)."
    )
    severity_level: Mapped[str] = mapped_column(
        String(16),
        nullable=False,
        doc="Categorized runtime criticality (Information, Warning, Critical)."
    )
    evtx_metadata: Mapped[Dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
        doc="Deserialized event properties and extensible forensic diagnostic parameters."
    )

    __table_args__ = (
        Index("idx_winlog_metadata_gin", "evtx_metadata", postgresql_using="gin"),
        {"comment": "Windows diagnostic logs featuring polymorphic GIN-indexed metadata."}
    )
